# Generated by Django 5.0.3 on 2024-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('AboutMe', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=50)),
                ('Skills1', models.CharField(max_length=50)),
                ('Skills2', models.CharField(max_length=50)),
                ('Skills3', models.CharField(max_length=50)),
                ('Skills4', models.CharField(max_length=50)),
                ('Skills5', models.CharField(max_length=50)),
                ('LanguagesKnown1', models.CharField(max_length=50)),
                ('LanguagesKnown2', models.CharField(max_length=50)),
                ('LanguagesKnown3', models.CharField(max_length=50)),
                ('sslc', models.CharField(max_length=50)),
                ('sslcyear', models.CharField(max_length=50)),
                ('sslcmark', models.CharField(max_length=50)),
                ('hsc', models.CharField(max_length=50)),
                ('hscyear', models.CharField(max_length=50)),
                ('hscmark', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('CollegeName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('cgpa', models.CharField(max_length=50)),
                ('ProjectTitle1', models.CharField(max_length=50)),
                ('ProjectTitle2', models.CharField(max_length=50)),
                ('Duration1', models.CharField(max_length=50)),
                ('Duration2', models.CharField(max_length=50)),
                ('Description1', models.CharField(max_length=50)),
                ('Description2', models.CharField(max_length=50)),
                ('AchievementType1', models.CharField(max_length=50)),
                ('AchievementType2', models.CharField(max_length=50)),
                ('AchievementType3', models.CharField(max_length=50)),
            ],
        ),
    ]
