# Generated by Django 5.0.3 on 2024-03-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calsy', '0002_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='dob',
        ),
    ]
