# Generated by Django 5.0.3 on 2024-03-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calsy', '0007_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
